version: '3.8'

services:

  # Serviço 1: O Banco de Dados (Postgres)
  db:
    image: postgres:16
    container_name: postgres-uex
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: laura
      POSTGRES_DB: desafio_uex
    ports:
      - "5432:5432"
    volumes:
      - postgres-data-uex:/var/lib/postgresql/data

  # Serviço 2: A Aplicação (Sua API)
  app:
    build: .
    container_name: app-uex
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/desafio_uex
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: laura
    depends_on:
      - db

volumes:
  postgres-data-uex: